[tool.poetry]
name = "hd3"
version = "0.1.0"
description = ""
authors = ["Jaivanth <94882495+Not-A-Psychic@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
